### ISSUE TITLE
python setup.py install vs. pip install

### ISSUE THREAD

**Issue by pquentin** [estebistec/django-twitter-bootstrap#20]
Running `python setup.py install` only produces one file in the virtualenv: `lib/python3.4/site-packages/django_twitter_bootstrap-3.2.0_1-py3.4.egg`.

However, running, `pip install django-twitter-bootstrap` produces `django_twitter_bootstrap-3.2.0_1-py3.4.egg-info` (so, +info) and `lib/python3.4/site-packages/twitter_bootstrap`. What's the difference? How can I properly install django-twitter-bootstrap with a local git clone?

Thank you.

**Comment by estebistec** [comment]
@pquentin Sorry for not noticing this (yikes, this must've gotten buried in a mark-as-read with a lot of other noise).

So, while this method of installation from source doesn't leave the folder behind, the `.egg` is pretty much a zip of the package, on the path and it should be importable (though, the static files may not be found this way).

However, why install this way as opposed to a typical pip install (where you get pretty much everything you need).

Now, if you're *dev'ing* on this package, then I would suggest a *dev-install* of the package. So instead of `python setup.py` install, do `pip install -e .`.

Tell me if I'm missing something else though.

**Comment by estebistec** [comment]
Also, given how long I missed this issue, perhaps I should relinquish primary maintenance of this package :/

Are you still using it much?

**Comment by pquentin** [comment]
Yeah, I was trying to fix an issue, and at the time I used `python setup.py install`. I now usually do `python setup.py develop` - thanks for mentioning `dev-isntall` and `pip install -e`!

No worries at all for the delay, it wasn't a blocking issue, and I used django-twitter-bootstrap for some time without issues. I did stop using django-twitter-bootstrap and I'm now including bootstrap as a git submodule - this has its own issues; I still don't know what's the best way to work with bootstrap for a project that is supposed to continue to evolve year after year.

Thank you for thinking about me!
